networks:
  appnetwork:
volumes:
  postgres_data:
  static_volume:
services:
  web:
    image: image_crud:1.0
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./stocks_products:/app
      - static_volume:/app/static
    depends_on:
      - db
    networks:
      - appnetwork

  db:
    image: postgres:alpine
    env_file:
      db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u admin -d stocks_products_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - appnetwork
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web
    networks:
      - appnetwork   